export default {
  '0e384e19': [() => import(/* webpackChunkName: '0e384e19' */ '@site/docs/intro.md'), '@site/docs/intro.md', require.resolveWeak('@site/docs/intro.md')],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ '@theme/DocItem'), '@theme/DocItem', require.resolveWeak('@theme/DocItem')],
  '1b481a15': [() => import(/* webpackChunkName: '1b481a15' */ '@site/docs/Usage/Components.md'), '@site/docs/Usage/Components.md', require.resolveWeak('@site/docs/Usage/Components.md')],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ '@theme/DocPage'), '@theme/DocPage', require.resolveWeak('@theme/DocPage')],
  '1f391b9e': [() => import(/* webpackChunkName: '1f391b9e' */ '@theme/MDXPage'), '@theme/MDXPage', require.resolveWeak('@theme/MDXPage')],
  '393be207': [() => import(/* webpackChunkName: '393be207' */ '@site/src/pages/markdown-page.md'), '@site/src/pages/markdown-page.md', require.resolveWeak('@site/src/pages/markdown-page.md')],
  '3ad6318f': [() => import(/* webpackChunkName: '3ad6318f' */ 'D:\\projects\\loick.team\\projects\\loickstyles\\LoickStyles\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json'), 'D:\\projects\\loick.team\\projects\\loickstyles\\LoickStyles\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json', require.resolveWeak('D:\\projects\\loick.team\\projects\\loickstyles\\LoickStyles\\.docusaurus\\docusaurus-plugin-content-docs\\default\\plugin-route-context-module-100.json')],
  '3c4545f8': [() => import(/* webpackChunkName: '3c4545f8' */ '@site/docs/Usage/Utilities.md'), '@site/docs/Usage/Utilities.md', require.resolveWeak('@site/docs/Usage/Utilities.md')],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ '@generated/docusaurus.config'), '@generated/docusaurus.config', require.resolveWeak('@generated/docusaurus.config')],
  '65a35267': [() => import(/* webpackChunkName: '65a35267' */ 'D:\\projects\\loick.team\\projects\\loickstyles\\LoickStyles\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json'), 'D:\\projects\\loick.team\\projects\\loickstyles\\LoickStyles\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json', require.resolveWeak('D:\\projects\\loick.team\\projects\\loickstyles\\LoickStyles\\.docusaurus\\docusaurus-plugin-content-pages\\default\\plugin-route-context-module-100.json')],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ '~docs/default/version-current-metadata-prop-751.json'), '~docs/default/version-current-metadata-prop-751.json', require.resolveWeak('~docs/default/version-current-metadata-prop-751.json')],
  'c4f5d8e4': [() => import(/* webpackChunkName: 'c4f5d8e4' */ '@site/src/pages/index.js'), '@site/src/pages/index.js', require.resolveWeak('@site/src/pages/index.js')],
  'dbcf8788': [() => import(/* webpackChunkName: 'dbcf8788' */ '@site/docs/Usage/Sections.md'), '@site/docs/Usage/Sections.md', require.resolveWeak('@site/docs/Usage/Sections.md')],};
